import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    overflow: "hidden",
    backgroundColor: "#FFF8DC",
  },
  content: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  bubble: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.55,
  },
  bubblePink: {
    width: 180,
    height: 180,
    top: -70,
    left: -70,
    backgroundColor: "#FFB4CF",
  },
  bubbleBlue: {
    width: 150,
    height: 150,
    top: 150,
    right: -85,
    backgroundColor: "#A9E4FF",
  },
  bubbleGreen: {
    width: 190,
    height: 190,
    bottom: -100,
    left: -60,
    backgroundColor: "#B8E986",
  },
  welcomePill: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 8,
    marginBottom: 14,
    elevation: 2,
    shadowColor: "#C58D22",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  welcomeText: {
    color: "#E96B3C",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  logoCard: {
    width: "100%",
    maxWidth: 340,
    aspectRatio: 1,
    padding: 7,
    borderRadius: 38,
    backgroundColor: "#FFFFFF",
    elevation: 10,
    shadowColor: "#5D3C16",
    shadowOpacity: 0.24,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
  },
  logo: {
    width: "100%",
    height: "100%",
    borderRadius: 32,
    resizeMode: "cover",
  },
  subtitle: {
    maxWidth: 320,
    marginTop: 20,
    color: "#5A4937",
    fontSize: 17,
    fontWeight: "700",
    lineHeight: 23,
    textAlign: "center",
  },
  playButton: {
    width: "100%",
    maxWidth: 330,
    minHeight: 68,
    marginTop: 22,
    paddingHorizontal: 12,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FF8A34",
    borderBottomWidth: 6,
    borderBottomColor: "#D85C18",
    elevation: 5,
  },
  playIconCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  playIcon: {
    width: 0,
    height: 0,
    marginLeft: 4,
    borderTopWidth: 9,
    borderBottomWidth: 9,
    borderLeftWidth: 15,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: "#FF8A34",
  },
  playText: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 0.5,
  },
  skillsRow: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
  },
  skillPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  skillPink: { backgroundColor: "#FFD1DF" },
  skillOrange: { backgroundColor: "#FFE09B" },
  skillBlue: { backgroundColor: "#C8EAFE" },
  skillText: {
    color: "#4A3F35",
    fontSize: 10,
    fontWeight: "900",
  },
  skillDot: {
    marginHorizontal: 7,
    color: "#A59888",
    fontSize: 16,
  },
});

export default styles;
