import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    overflow: "hidden",
    backgroundColor: "#F3F9FF",
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 28,
  },
  decoration: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.5,
  },
  decorationTop: {
    width: 210,
    height: 210,
    top: -110,
    right: -85,
    backgroundColor: "#FFE18A",
  },
  decorationBottom: {
    width: 180,
    height: 180,
    bottom: -90,
    left: -90,
    backgroundColor: "#CDB2FF",
  },
  header: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    elevation: 3,
    shadowColor: "#42617D",
    shadowOpacity: 0.15,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 3 },
  },
  backIcon: {
    marginTop: -5,
    color: "#26384A",
    fontSize: 42,
    fontWeight: "700",
    lineHeight: 44,
  },
  logo: {
    width: 82,
    height: 82,
    borderRadius: 22,
    borderWidth: 4,
    borderColor: "#FFFFFF",
  },
  headerSpacer: {
    width: 46,
  },
  titleBlock: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 28,
  },
  eyebrow: {
    color: "#F07B32",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.1,
  },
  title: {
    maxWidth: 340,
    marginTop: 7,
    color: "#243A50",
    fontSize: 29,
    fontWeight: "900",
    lineHeight: 34,
    textAlign: "center",
  },
  subtitle: {
    marginTop: 7,
    color: "#6D7E8F",
    fontSize: 16,
    fontWeight: "600",
  },
  modeCard: {
    width: "100%",
    minHeight: 122,
    marginBottom: 18,
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderRadius: 28,
    borderBottomWidth: 6,
    flexDirection: "row",
    alignItems: "center",
    elevation: 5,
  },
  infiniteCard: {
    backgroundColor: "#D7B8FF",
    borderBottomColor: "#A77AE2",
  },
  levelsCard: {
    backgroundColor: "#9BE38D",
    borderBottomColor: "#5EBC54",
  },
  iconCircle: {
    width: 76,
    height: 76,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  infiniteIconCircle: {
    backgroundColor: "#8051BD",
  },
  levelsIconCircle: {
    backgroundColor: "#338F4D",
  },
  infinityIcon: {
    color: "#FFFFFF",
    fontSize: 52,
    fontWeight: "800",
    lineHeight: 58,
  },
  numberIcon: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 1,
  },
  cardCopy: {
    flex: 1,
    marginLeft: 15,
    marginRight: 8,
  },
  cardTitle: {
    color: "#203040",
    fontSize: 20,
    fontWeight: "900",
  },
  cardDescription: {
    marginTop: 5,
    color: "#3E5061",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 19,
  },
  cardArrowCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.75)",
  },
  cardArrow: {
    marginTop: -3,
    color: "#26384A",
    fontSize: 34,
    fontWeight: "700",
    lineHeight: 35,
  },
  tipCard: {
    marginTop: 6,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 2,
    borderColor: "#E3EDF5",
  },
  starBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFD84D",
  },
  star: {
    color: "#FFFFFF",
    fontSize: 22,
  },
  tipText: {
    flex: 1,
    marginLeft: 12,
    color: "#617181",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
});

export default styles;
